const PREFIX = 'IAMNOBILIS@@'

export const GENERATE_CHARACTER = PREFIX + 'GENERATE_CHARACTER'
export const SET_CHARACTER = PREFIX + 'SET_CHARACTER'
export const SET_ESTATE = PREFIX + 'SET_ESTATE'
export const SET_LOADING = PREFIX + 'SET_LOADING'
